export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
];

export const footerLinks = [
  {
    title: "Menu",
    links: [
      { title: "Home", url: "/" },
      { title: "Car Catalogue", url: "/" },
      { title: "Services", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "About us", url: "/" },
      { title: "Careers", url: "/" },
      { title: "Contact us", url: "/" },
    ],
  },
  {
    title: "Further Information",
    links: [
      { title: "Terms & Conditions", url: "/" },
      { title: "Privacy Policy", url: "/" },
    ],
  },
  {
    title: "Social media",
    links: [
      {
        title: "Github",
        url: "https://github.com/olamgir95",
        icon: "/github.svg",
      },
      {
        title: "Discord",
        url: "/",
        icon: "/discord.svg",
      },
      {
        title: "LinkedIn",
        url: "https://www.linkedin.com/in/olamgir-ollomurodov-228571270/",
        icon: "/linkedin.svg",
      },
    ],
    isSocialMedia: true,
  },
];
